### ISSUE TITLE
How Do I Install this

### ISSUE THREAD

**Issue by g2132324** [ikkehman/new-wibot-anime-whatsapp-bot#3]
i'm new here and i can't understand ur instructions. can u give a more detailed instructions

**Comment by ikkehman** [comment]
Fisrt u need to install NPM. For Ubuntu use this:
`sudo apt install nodejs npm`
then install git
`sudo apt install git`

after finished, clone this repo
`git clone https://github.com/ikkehman/new-wibot-anime-whatsapp-bot.git`
and open folder by this command
`cd new-wibot-anime-whatsapp-bot`.

now u can start installation by command
`npm install`
after installation finished, start bot
`npm start`

**Comment by g2132324** [comment]
Thank you but where do i use the "sudo apt install nodejs npm"

**Comment by g2132324** [comment]
And which api should i use

**Comment by ikkehman** [comment]
> Thank you but where do i use the "sudo apt install nodejs npm"

on your terminal


> And which api should i use

u can get api here:
"nao": https://saucenao.com/user.php?page=search-api
"xteam": https://xteam.xyz/
"lol":  https://api.lolhuman.xyz/
